### ISSUE TITLE
Support listen for device

### ISSUE THREAD

**Issue by rym002** [rodrigorc/inputmap#1]
Request to support listening for a connected device. An example use case would be to leave inputmap running possibly using systemd. When the device becomes available e.g. steam controller turned on, the device would then be mapped.

**Comment by rym002** [comment]
I was able to accomplish my objective using systemd. The first time the controller is turned on, it will start inputmap. The service remains running after turning off the controller. The uinput device remains after and is reconnected when restarted. The only issue here is I have to duplicate the config for each serial number, it would be nice if I can pass in the serial as an argument.

```
# /etc/udev/rules.d/99-inputmap.rules
SUBSYSTEM=="input", ATTRS{name}=="Wireless Steam Controller", TAG+="systemd", ENV{SYSTEMD_WANTS}="inputmap@%s{uniq}.service"
```

```
# /etc/systemd/system/inputmap@.service
[Unit]
Description=%i service for inputmap

[Service]
ExecStart=/usr/bin/inputmap /etc/inputmap/xbox.%i.ini
```

**Comment by rodrigorc** [comment]
Listening for connected devices is certainly a worthy feature, but it is not so easy to implement, because we have to handle disconnections too, and we have to avoid entering infinite loops (output devices are actually also input devices, so we will get events for these too). I'll work on it.

But your systemd solution for a dedicated gamebox is quite nice. I've pushed a change to be able to use some kind of macros in the config file, that should make your system easier.

Now your systemd config would have something like:
```
ExecStart=/usr/bin/inputmap -a SERIAL=%i /etc/inputmap/xbox.ini
```
And then in the `xbox.ini` replace your serial number with the generic line:
```
serial={SERIAL}
```

**Comment by rym002** [comment]
Cool, will test this out. This may solve issue #2 also as it simplifies the config.

**Comment by rodrigorc** [comment]
As a side note, I would like to add your systemd configuration to the README, I think it makes a nice addition. If you could send a pull-request to get the proper credit, that would be great.
