### ISSUE TITLE
Support for multiple steam controllers

### ISSUE THREAD

**Issue by rym002** [rodrigorc/inputmap#2]
Is it possible to support multiple steam controllers without duplicating the configuration. My observation is when the serial number is not specified its connected to the first found device. The only way I was able to run 2 controllers is to copy the config and set the unique serial in each.

**Comment by rodrigorc** [comment]
I'm not sure what you need here. I think that currently you have two copies of the config file, each with a serial number and you are running two instances of `inputmap`. Is that correct?

You could write a single config file without the serial number and run two instances of `inputmap` but I think that without the serial both will detect the same device, won't they? That could be easily fixed with locked files, I think.

Or you could write a single config file with two separated `[input]` or `[steam]` sections and two `[output]` sections. I don't have two steam controllers but I think something like this might work:
```
[steam]
name=Steam1

[steam]
name=Steam2

[output]
name=Microsoft X-Box 360 pad
ABS_X  = Steam1.StickX
...

[output]
name=Microsoft X-Box 360 pad
ABS_X  = Steam2.StickX
...
```
Naturally you still have to specify the `[output]` twice!

Avoiding the duplication is tricky because of the `[variables]` section and that I want to keep the ability to map one input to N outputs or N inputs to one output.

Maybe we could try some kind of template:
```
[steam]
name=Steam%

[variables]
xx%=Steam%.StickX * 2

[output]
name=Microsoft X-Box 360 pad
ABS_X  = xx%
ABS_Y  = Steam%.StickX
```
And then, in runtime, every Steam Controller will get a different number and instantiate a different set of variables and output devices. Would this work for you?

**Comment by rym002** [comment]
I think it would get messy to combine multiple mappings, with the ability to pass in variables as mentioned in #1 this could be closed. Code will probably be cleaner since you would run multiple instances to support each controller and can mix and match as desired.
